/**
 * ADMIN CHOICES:
 * The purpose of this program is to provide the administrator with options that they can choose from.
 * For instance, the administrator has the options of creating or searching an account, transferring money from an account,
 * applying interest charges, and of closing an account as well. The administrator can use these options to manipulate a 
 * bank account in a variety of ways.
 *
 * @author Chamera and Kash
 * @version 06/15/17
 */
public class AdminChoices extends javax.swing.JFrame {

    /**
     * Creates new constructor for  AdminChoices
     */
    public AdminChoices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createAcnt = new javax.swing.JButton();
        searchingBtn = new javax.swing.JButton();
        btn_transfer = new javax.swing.JButton();
        btn_interestCharges = new javax.swing.JButton();
        btn_closingAccount = new javax.swing.JButton();
        btn_signout = new javax.swing.JButton();
        lbl_ckbank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 26, 53));

        createAcnt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        createAcnt.setForeground(new java.awt.Color(0, 26, 53));
        createAcnt.setText("Create An Account");
        createAcnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAcntActionPerformed(evt);
            }
        });

        searchingBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        searchingBtn.setForeground(new java.awt.Color(0, 26, 53));
        searchingBtn.setText("Search An Account");
        searchingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingBtnActionPerformed(evt);
            }
        });

        btn_transfer.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_transfer.setForeground(new java.awt.Color(0, 26, 53));
        btn_transfer.setText("Transfer");
        btn_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transferActionPerformed(evt);
            }
        });

        btn_interestCharges.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_interestCharges.setForeground(new java.awt.Color(0, 26, 53));
        btn_interestCharges.setText("Interest Charges");
        btn_interestCharges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_interestChargesActionPerformed(evt);
            }
        });

        btn_closingAccount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_closingAccount.setForeground(new java.awt.Color(0, 26, 53));
        btn_closingAccount.setText("Closing An Account");
        btn_closingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closingAccountActionPerformed(evt);
            }
        });

        btn_signout.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_signout.setForeground(new java.awt.Color(0, 26, 53));
        btn_signout.setText("Sign Out");
        btn_signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signoutActionPerformed(evt);
            }
        });

        lbl_ckbank.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbl_ckbank.setForeground(new java.awt.Color(51, 61, 174));
        lbl_ckbank.setText("Ck BANK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_closingAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(btn_interestCharges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createAcnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_signout)
                    .addComponent(lbl_ckbank))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_ckbank)
                .addGap(18, 18, 18)
                .addComponent(createAcnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchingBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_interestCharges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_closingAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_signout)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This method allows the user to proceed onto the CreateAccount class.
     * 
     * * @param evt Holds data of the action performed by the user on the control.           
     */
     
    private void createAcntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAcntActionPerformed
        this.setVisible(false);
        CreateAccount createAccount = new CreateAccount();
        createAccount.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_createAcntActionPerformed
/**
 * This method proceeds onto the searchingPage under the action of the administrator.
 * 
  * @param evt Holds data of the action performed by the user on the control.           
  */
    private void searchingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingBtnActionPerformed
       this.setVisible(false);
        SearchingPage searchPage = new SearchingPage();
        searchPage.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_searchingBtnActionPerformed
 /**
     * This method allows the user to proceed onto the TransferAccount class.
     * 
     * * @param evt Holds data of the action performed by the user on the control.           
     */
    private void btn_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transferActionPerformed
          this.setVisible(false);
        TransferPage transPage = new TransferPage();
        transPage.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btn_transferActionPerformed
 /**
     * This method allows the user to proceed onto the ClosingAccount class.
     * 
     * * @param evt Holds data of the action performed by the user on the control.           
     */
    private void btn_closingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closingAccountActionPerformed
        this.setVisible(false);
        ClosingAcnt closingAcnt = new ClosingAcnt();
        closingAcnt.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_btn_closingAccountActionPerformed
 /**
     * This method allows the user to proceed onto the FrontPage class.
     * 
     * * @param evt Holds data of the action performed by the user on the control.           
     */
    private void btn_signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signoutActionPerformed
        this.setVisible(false);
        FrontPage frontPage = new FrontPage();
        frontPage.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btn_signoutActionPerformed
 /**
     * This method allows the user to proceed onto the InterestPage class.
     * 
     * * @param evt Holds data of the action performed by the user on the control.           
     */
    private void btn_interestChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_interestChargesActionPerformed
       this.setVisible(false);
        InterestPage interestPage = new InterestPage();
        interestPage.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btn_interestChargesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChoices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_closingAccount;
    private javax.swing.JButton btn_interestCharges;
    private javax.swing.JButton btn_signout;
    private javax.swing.JButton btn_transfer;
    private javax.swing.JButton createAcnt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ckbank;
    private javax.swing.JButton searchingBtn;
    // End of variables declaration//GEN-END:variables
}
