
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 * CLOSE AN ACCOUNT:
 * The purpose of this program is to close an account after a certain account number has been entered.
 * This program will check if the account number exists and will then continue to close the account. 
 *
 * @author Chamera and Kash
 */
public class ClosingAcnt extends javax.swing.JFrame {

    /**
     * Creates new constructor from ClosingAcnt
     */
    public ClosingAcnt() {
        initComponents();
         mainMenuBtn.setVisible(false);
        signOutBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accountInfoLbl = new javax.swing.JLabel();
        accountNumLbl = new javax.swing.JLabel();
        accountNumField = new javax.swing.JTextField();
        closeAccountBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        signOutBtn = new javax.swing.JButton();
        lbl_ckbank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 26, 53));

        accountInfoLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        accountInfoLbl.setForeground(new java.awt.Color(255, 255, 255));

        accountNumLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        accountNumLbl.setForeground(new java.awt.Color(255, 255, 255));
        accountNumLbl.setText("Account Number");

        accountNumField.setBackground(new java.awt.Color(255, 255, 255));
        accountNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumFieldActionPerformed(evt);
            }
        });

        closeAccountBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        closeAccountBtn.setForeground(new java.awt.Color(0, 26, 53));
        closeAccountBtn.setText("Close Account");
        closeAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAccountBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(0, 26, 53));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        signOutBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        signOutBtn.setForeground(new java.awt.Color(0, 26, 53));
        signOutBtn.setText("Sign Out");
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        lbl_ckbank.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbl_ckbank.setForeground(new java.awt.Color(51, 61, 174));
        lbl_ckbank.setText("Ck BANK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(closeAccountBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(accountInfoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(accountNumLbl)
                                .addGap(38, 38, 38)
                                .addComponent(accountNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ckbank, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mainMenuBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signOutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_ckbank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountInfoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumLbl)
                    .addComponent(accountNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(closeAccountBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(mainMenuBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signOutBtn)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void accountNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumFieldActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_accountNumFieldActionPerformed
       /** This method checks whether the account number given by the administrator
        * exists. If the account number exists the method will class out to the ATM 
        * class to remove the account. However, if it does not exist a message pops
        * up to tell the administrator that the account does not exist.
        * 
         * @param evt Holds data of the action performed by the user on the control.           
         */
    private void closeAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAccountBtnActionPerformed
    UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "Century Gothic", Font.PLAIN, 12))); 
        if(ATM.accountExist(Integer.parseInt(accountNumField.getText()))==false)
            {
             JOptionPane.showMessageDialog(this, "Account does not exist.");  
              accountNumField.setText("");   
            }
        else
        ATM.closeAnAccount(Integer.parseInt(accountNumField.getText()));
     mainMenuBtn.setVisible(true);
        signOutBtn.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_closeAccountBtnActionPerformed
        /** This method allows the user to proceed onto the AdminChoices class.
         * 
         * @param evt Holds data of the action performed by the user on the control.           
         */
    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
       this.setVisible(false);
        AdminChoices adminChoices = new AdminChoices();
        adminChoices.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuBtnActionPerformed

      /** This method allows the user to proceed onto the FrontPage class.
         * 
         * @param evt Holds data of the action performed by the user on the control.           
         */
    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        this.setVisible(false);
        FrontPage frontPage = new FrontPage();
        frontPage.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_signOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClosingAcnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClosingAcnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClosingAcnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClosingAcnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClosingAcnt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountInfoLbl;
    private javax.swing.JTextField accountNumField;
    private javax.swing.JLabel accountNumLbl;
    private javax.swing.JButton closeAccountBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ckbank;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton signOutBtn;
    // End of variables declaration//GEN-END:variables
}
