/**
 * DEPOSIT PAGE:
 * The purpose of this program is to deposit money into the desired account, either chequings or savings account. 
 * For instance, the program will check whether the amounts to be desposited are greater than 0, and will then deposit the money
 * into the appropriate account. 
 * 
 * @author Chamera and Kash
 */
public class DepositePage extends javax.swing.JFrame {

    /**
     * Creates new form DepositePage
     */
    public DepositePage() {
        initComponents();
           mainMenuBtn.setVisible(false);
        signOutBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbx_amount = new javax.swing.JComboBox<>();
        btn_savings = new javax.swing.JButton();
        btn_desposits = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        signOutBtn = new javax.swing.JButton();
        lbl_ckbank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 26, 53));

        cbx_amount.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbx_amount.setForeground(new java.awt.Color(0, 26, 53));
        cbx_amount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amount", "20", "50", "100", "500", "1000" }));
        cbx_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_amountActionPerformed(evt);
            }
        });

        btn_savings.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_savings.setForeground(new java.awt.Color(0, 26, 53));
        btn_savings.setText("Deposit to Savings");
        btn_savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_savingsActionPerformed(evt);
            }
        });

        btn_desposits.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btn_desposits.setForeground(new java.awt.Color(0, 26, 53));
        btn_desposits.setText("Deposit to Chequing");
        btn_desposits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_despositsActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(0, 26, 53));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        signOutBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        signOutBtn.setForeground(new java.awt.Color(0, 26, 53));
        signOutBtn.setText("Sign Out");
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        lbl_ckbank.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbl_ckbank.setForeground(new java.awt.Color(51, 61, 174));
        lbl_ckbank.setText("Ck BANK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cbx_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_desposits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_savings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mainMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_ckbank, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_ckbank)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btn_desposits)
                        .addGap(18, 18, 18)
                        .addComponent(btn_savings))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cbx_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(mainMenuBtn)
                .addGap(7, 7, 7)
                .addComponent(signOutBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_amountActionPerformed
/**
 * This method adds the value that is deposited in, into the savings accounts.
 * 
 * @param evt 
 */
    private void btn_savingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_savingsActionPerformed
            ATM.depositSavings(Integer.parseInt((String) cbx_amount.getSelectedItem()));   
             mainMenuBtn.setVisible(true);
        signOutBtn.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_savingsActionPerformed
/**
 * This method adds the value that is deposited in, into the chequing accounts.
 * 
 * @param evt 
 */
    private void btn_despositsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_despositsActionPerformed
             ATM.depositChequing(Integer.parseInt((String) cbx_amount.getSelectedItem()));  
              mainMenuBtn.setVisible(true);
        signOutBtn.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btn_despositsActionPerformed
/**
 * This method allows the user to proceed to the UserChoices for users.
 * @param evt 
 */
    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        this.setVisible(false);
        UserChoices userChoices = new UserChoices();
        userChoices.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mainMenuBtnActionPerformed
/**
 * This method allows the user to proceed to the FrontPage for users.
 * @param evt 
 */
    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        this.setVisible(false);
        FrontPage frontPage = new FrontPage();
        frontPage.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_signOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_desposits;
    private javax.swing.JButton btn_savings;
    private javax.swing.JComboBox<String> cbx_amount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ckbank;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton signOutBtn;
    // End of variables declaration//GEN-END:variables
}
