
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 * TRANSFER PAGE:
 * The purpose of this account is to display the information contained within a specific bank account after a certain
 * account number is entered. This program will check to see whether the account number entered is valid, and will
 * then display information such as the chequing and savings balances as well as the account holder's names. 
 * @author Chamera and Kash
 */
public class TransferPage extends javax.swing.JFrame {

    private static int cOrS;
    private static int cOrS2;

    /**
     * Creates new form TransferPage
     */
    public TransferPage() {
        initComponents();
        mainMenuBtn.setVisible(false);
        signOutBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        transferTitle = new javax.swing.JLabel();
        acntTypeLbl = new javax.swing.JLabel();
        fromLbl = new javax.swing.JLabel();
        toLbl = new javax.swing.JLabel();
        chequingBtn1 = new javax.swing.JToggleButton();
        savingsBtn1 = new javax.swing.JToggleButton();
        acntNumField1 = new javax.swing.JTextField();
        acntNumLbl2 = new javax.swing.JLabel();
        acntNum2 = new javax.swing.JTextField();
        accountTypeLbl2 = new javax.swing.JLabel();
        chequingbTN2 = new javax.swing.JToggleButton();
        acntNumLbl = new javax.swing.JLabel();
        savingBtn2 = new javax.swing.JToggleButton();
        amountLbl = new javax.swing.JLabel();
        signOutBtn = new javax.swing.JButton();
        amountField = new javax.swing.JTextField();
        transferBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        lbl_ckbank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 26, 53));

        acntTypeLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        acntTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        acntTypeLbl.setText("ACCOUNT TYPES ");

        fromLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fromLbl.setForeground(new java.awt.Color(255, 255, 255));
        fromLbl.setText("FROM");

        toLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toLbl.setForeground(new java.awt.Color(255, 255, 255));
        toLbl.setText("TO");

        chequingBtn1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        chequingBtn1.setForeground(new java.awt.Color(0, 26, 53));
        chequingBtn1.setText("Chequing");
        chequingBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequingBtn1ActionPerformed(evt);
            }
        });

        savingsBtn1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        savingsBtn1.setForeground(new java.awt.Color(0, 26, 53));
        savingsBtn1.setText("Savings");
        savingsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsBtn1ActionPerformed(evt);
            }
        });

        acntNumField1.setBackground(new java.awt.Color(255, 255, 255));
        acntNumField1.setForeground(new java.awt.Color(0, 0, 0));
        acntNumField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acntNumField1ActionPerformed(evt);
            }
        });

        acntNumLbl2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        acntNumLbl2.setForeground(new java.awt.Color(255, 255, 255));
        acntNumLbl2.setText("ACCOUNT NUMBER");

        acntNum2.setBackground(new java.awt.Color(255, 255, 255));

        accountTypeLbl2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        accountTypeLbl2.setForeground(new java.awt.Color(255, 255, 255));
        accountTypeLbl2.setText("ACCOUNT TYPES ");

        chequingbTN2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        chequingbTN2.setForeground(new java.awt.Color(0, 26, 53));
        chequingbTN2.setText("Chequing");
        chequingbTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequingbTN2ActionPerformed(evt);
            }
        });

        acntNumLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        acntNumLbl.setForeground(new java.awt.Color(255, 255, 255));
        acntNumLbl.setText("ACCOUNT NUMBER");

        savingBtn2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        savingBtn2.setForeground(new java.awt.Color(0, 26, 53));
        savingBtn2.setText("Savings");
        savingBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingBtn2ActionPerformed(evt);
            }
        });

        amountLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        amountLbl.setForeground(new java.awt.Color(255, 255, 255));
        amountLbl.setText("AMOUNT");

        signOutBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        signOutBtn.setForeground(new java.awt.Color(0, 26, 53));
        signOutBtn.setText("Sign Out");
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        amountField.setBackground(new java.awt.Color(255, 255, 255));
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        transferBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        transferBtn.setForeground(new java.awt.Color(0, 26, 53));
        transferBtn.setText("Transfer");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(0, 26, 53));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        lbl_ckbank.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbl_ckbank.setForeground(new java.awt.Color(51, 61, 174));
        lbl_ckbank.setText("Ck BANK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(transferTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(51, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accountTypeLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(acntNumLbl)
                                            .addComponent(acntNumLbl2))
                                        .addGap(0, 39, Short.MAX_VALUE))
                                    .addComponent(acntTypeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(amountLbl)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(transferBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(chequingBtn1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(savingsBtn1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lbl_ckbank))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(acntNumField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(chequingbTN2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(savingBtn2)))
                                            .addComponent(acntNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(mainMenuBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(signOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(fromLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_ckbank)
                .addGap(10, 10, 10)
                .addComponent(fromLbl)
                .addGap(12, 12, 12)
                .addComponent(transferTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acntNumLbl2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acntNumField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acntTypeLbl)
                        .addComponent(chequingbTN2))
                    .addComponent(savingBtn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(toLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acntNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acntNumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTypeLbl2)
                    .addComponent(chequingBtn1)
                    .addComponent(savingsBtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLbl)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signOutBtn)
                    .addComponent(mainMenuBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 342));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed
 /** This method checks to see that the transfer between the two accounts is possible, it 
  * determines whether the first account has sufficient funds to transfer to another account. 
  * It also checks if the value of the amount is negative, or if the account number doesn't
  * seem to exist.
  * 
   * @param evt Holds data of the action performed by the user on the control.           
   */
    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "Century Gothic", Font.PLAIN, 12))); 
        if(ATM.accountExist(Integer.parseInt(acntNumField1.getText()))==false)
        {
          JOptionPane.showMessageDialog(this, "Account does not exist.");   
          acntNumField1.setText("");
        }
        else if(ATM.accountExist(Integer.parseInt(acntNum2.getText()))==false)
        {
          JOptionPane.showMessageDialog(this, "Account does not exist.");  
          acntNum2.setText("");
        }
        else if(Double.parseDouble(amountField.getText())<0)  
        {
          JOptionPane.showMessageDialog(this, "Amount cannot be a negative value.");  
         amountField.setText("");  
        }
        else if((ATM.sufficientAmount(Integer.parseInt(acntNumField1.getText()), cOrS, Double.parseDouble(amountField.getText())))==false)
        {
         JOptionPane.showMessageDialog(this, "Account does not have sufficient funds.");  
         amountField.setText("");
        }
        else
        ATM.transfer(Integer.parseInt(acntNumField1.getText()), cOrS, Integer.parseInt(acntNum2.getText()), cOrS2,Double.parseDouble(amountField.getText())); 
        mainMenuBtn.setVisible(true);
        signOutBtn.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_transferBtnActionPerformed
 /** This method stores a value of 1 or 2, depending on the 
  * type of account selected; chequing or savings. In this case, this method is chequing, since the chequing button was clicked.
  * 
   * @param evt Holds data of the action performed by the user on the control.           
   */
    private void chequingbTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequingbTN2ActionPerformed
           cOrS2=1;          // TODO add your handling code here:
    }//GEN-LAST:event_chequingbTN2ActionPerformed
/** This method stores a value of 1 or 2, depending on the 
  * type of account selected; chequing or savings. In this case, this method is savings, since the savings button was clicked.
  * 
   * @param evt Holds data of the action performed by the user on the control.           
   */
    private void savingBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingBtn2ActionPerformed
        cOrS2=2;// TODO add your handling code here:
    }//GEN-LAST:event_savingBtn2ActionPerformed
/** This method stores a value of 1 or 2, depending on the 
  * type of account selected; chequing or savings. In this case, this method is chequing, since the chequing button was clicked.
  * 
   * @param evt Holds data of the action performed by the user on the control.           
   */
    private void chequingBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequingBtn1ActionPerformed
        cOrS=1;        // TODO add your handling code here:
    }//GEN-LAST:event_chequingBtn1ActionPerformed
/** This method stores a value of 1 or 2, depending on the 
  * type of account selected; chequing or savings. In this case, this method is savings, since the savings button was clicked.
  * 
   * @param evt Holds data of the action performed by the user on the control.           
   */
    private void savingsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsBtn1ActionPerformed
        cOrS=2;          // TODO add your handling code here:
    }//GEN-LAST:event_savingsBtn1ActionPerformed
        /** This method allows the user to proceed onto the AdminChoices class.
         * 
         * @param evt Holds data of the action performed by the user on the control.           
         */
    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
         this.setVisible(false);
        AdminChoices adminChoices = new AdminChoices();
        adminChoices.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuBtnActionPerformed
        /** This method allows the user to proceed onto the FrontPage class.
         * 
         * @param evt Holds data of the action performed by the user on the control.           
         */
    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
       this.setVisible(false);
        FrontPage frontPage = new FrontPage();
        frontPage.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void acntNumField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acntNumField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acntNumField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountTypeLbl2;
    private javax.swing.JTextField acntNum2;
    private javax.swing.JTextField acntNumField1;
    private javax.swing.JLabel acntNumLbl;
    private javax.swing.JLabel acntNumLbl2;
    private javax.swing.JLabel acntTypeLbl;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JToggleButton chequingBtn1;
    private javax.swing.JToggleButton chequingbTN2;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ckbank;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JToggleButton savingBtn2;
    private javax.swing.JToggleButton savingsBtn1;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JLabel toLbl;
    private javax.swing.JButton transferBtn;
    private javax.swing.JLabel transferTitle;
    // End of variables declaration//GEN-END:variables
}
