
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 * The purpose of this account is to display the information contained within a specific bank account after a certain
 * account number is entered. This program will check to see whether the account number entered is valid, and will
 * then display information such as the chequing and savings balances as well as the account holder's names.
 *
 * @author Chamera and Kash
 */
public class TransferPageUser extends javax.swing.JFrame {

    private static int CorS;
    private static int CorS2;

    /**
     * Creates new construct for TransferPageUser
     */
    public TransferPageUser() {
        initComponents();
        mainMenuBtn.setVisible(false);
        signOutBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        savingsBtn = new javax.swing.JToggleButton();
        chequingBtn = new javax.swing.JToggleButton();
        accountNum = new javax.swing.JTextField();
        accountSavingBtn = new javax.swing.JToggleButton();
        accountChequingBtn = new javax.swing.JToggleButton();
        amountField = new javax.swing.JTextField();
        amountLbl = new javax.swing.JLabel();
        transferBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        signOutBtn = new javax.swing.JButton();
        toLbl = new javax.swing.JLabel();
        fromLbl = new javax.swing.JLabel();
        ckBankLbl = new javax.swing.JLabel();
        accountNumLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 26, 53));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        savingsBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        savingsBtn.setForeground(new java.awt.Color(0, 26, 53));
        savingsBtn.setText("Savings");
        savingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsBtnActionPerformed(evt);
            }
        });

        chequingBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        chequingBtn.setForeground(new java.awt.Color(0, 26, 53));
        chequingBtn.setText("Chequing");
        chequingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequingBtnActionPerformed(evt);
            }
        });

        accountNum.setBackground(new java.awt.Color(255, 255, 255));

        accountSavingBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        accountSavingBtn.setForeground(new java.awt.Color(0, 26, 53));
        accountSavingBtn.setText("Savings");
        accountSavingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSavingBtnActionPerformed(evt);
            }
        });

        accountChequingBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        accountChequingBtn.setForeground(new java.awt.Color(0, 26, 53));
        accountChequingBtn.setText("Chequing");
        accountChequingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChequingBtnActionPerformed(evt);
            }
        });

        amountField.setBackground(new java.awt.Color(255, 255, 255));

        amountLbl.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        amountLbl.setForeground(new java.awt.Color(255, 255, 255));
        amountLbl.setText("Amount");

        transferBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        transferBtn.setForeground(new java.awt.Color(0, 26, 53));
        transferBtn.setText("Transfer");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(0, 26, 53));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        signOutBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        signOutBtn.setForeground(new java.awt.Color(0, 26, 53));
        signOutBtn.setText("Sign Out");
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        toLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        toLbl.setForeground(new java.awt.Color(255, 255, 255));
        toLbl.setText("TO");

        fromLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fromLbl.setForeground(new java.awt.Color(255, 255, 255));
        fromLbl.setText("FROM");

        ckBankLbl.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        ckBankLbl.setForeground(new java.awt.Color(51, 61, 174));
        ckBankLbl.setText("Ck BANK");

        accountNumLbl.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        accountNumLbl.setForeground(new java.awt.Color(255, 255, 255));
        accountNumLbl.setText("Account Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(toLbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(accountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(amountLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chequingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(savingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(fromLbl))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(transferBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(accountChequingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(accountSavingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(accountNumLbl)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(mainMenuBtn)
                                .addGap(4, 4, 4)
                                .addComponent(signOutBtn))
                            .addComponent(ckBankLbl, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ckBankLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fromLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chequingBtn)
                    .addComponent(savingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(toLbl)
                .addGap(11, 11, 11)
                .addComponent(accountNumLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountChequingBtn)
                    .addComponent(accountSavingBtn)
                    .addComponent(accountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLbl)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signOutBtn)
                    .addComponent(mainMenuBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * This method checks to see that the user's saving or chequing depending on the
 * account chosen, has sufficient funds to go through a transfer. The method makes
 * sure that the amount is a negative value, and that the account the money is 
 * transferred to exists. The method then calls to the ATM class, which allows the
 * transfer to occur.
 * 
 * @param evt 
 */
    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "Century Gothic", Font.PLAIN, 12))); 
        if(ATM.sufficientAmountTransfer(CorS, Double.parseDouble(amountField.getText()))==false)
        {
           JOptionPane.showMessageDialog(this, "Account does not have sufficient funds.");  
              amountField.setText("");    
        }
        else if(Double.parseDouble(amountField.getText())<0)
        {
          JOptionPane.showMessageDialog(this, "Amount cannot be a negative value.");  
              amountField.setText("");   
        }
        else if(ATM.accountExist(Integer.parseInt(accountNum.getText()))==false)
        {
           JOptionPane.showMessageDialog(this, "Account does not exist.");  
              accountNum.setText("");    
        }
        ATM.transfer(CorS, Integer.parseInt(accountNum.getText()), CorS2, Double.parseDouble(amountField.getText()));
        mainMenuBtn.setVisible(true);
        signOutBtn.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_transferBtnActionPerformed
/**
 * The method assign the static variable CorS to 1 to indicate that the user has chosen 
 * the savings account.
 * @param evt 
 */
    private void savingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsBtnActionPerformed
         CorS = 1; // TODO add your handling code here:
    }//GEN-LAST:event_savingsBtnActionPerformed
/**
 * The method assign the static variable CorS to 2 to indicate that the user has chosen 
 * the chequing account.
 * @param evt 
 */
    private void chequingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequingBtnActionPerformed
        CorS=2;// TODO add your handling code here:
    }//GEN-LAST:event_chequingBtnActionPerformed
/**
 * The method assign the static variable CorS2 to 1 to indicate that the user has chosen 
 * to send his fund to the account's savings account.
 * @param evt 
 */
    private void accountSavingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSavingBtnActionPerformed
        CorS2=1;        // TODO add your handling code here:
    }//GEN-LAST:event_accountSavingBtnActionPerformed
/**
 * The method assign the static variable CorS2 to 2 to indicate that the user has chosen 
 * to send his fund to the account's chequing account.
 * @param evt 
 */
    private void accountChequingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChequingBtnActionPerformed
        CorS2=2;        // TODO add your handling code here:
    }//GEN-LAST:event_accountChequingBtnActionPerformed
/**
 * This method allows the user to proceed to the UserChoices for users.
 * @param evt 
 */
    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        this.setVisible(false);
        UserChoices userChoices = new UserChoices();
        userChoices.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuBtnActionPerformed
/**
 * This method allows the user to proceed to the FrontPage for users.
 * @param evt 
 */
    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
       this.setVisible(false);
        FrontPage frontPage = new FrontPage();
        frontPage.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_signOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferPageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferPageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton accountChequingBtn;
    private javax.swing.JTextField accountNum;
    private javax.swing.JLabel accountNumLbl;
    private javax.swing.JToggleButton accountSavingBtn;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLbl;
    private javax.swing.JToggleButton chequingBtn;
    private javax.swing.JLabel ckBankLbl;
    private javax.swing.JLabel fromLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JToggleButton savingsBtn;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JLabel toLbl;
    private javax.swing.JButton transferBtn;
    // End of variables declaration//GEN-END:variables
}
