
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 * WITHDRAWL:
 * The purpose of this program is to withdraw the desired amount from a certain bank account.
 * This program will only allow the user to withdraw money from their account if the accounts have sufficient funds.
 * The user can also only withdraw money in specific amounts of either 20, 50, 100, 500, and 1000. 
 *
 * @author Chamera and Kash
 */
public class Withdrawl extends javax.swing.JFrame {

    /**
     * Creates new constructor for Withdrawl
     */
    public Withdrawl() {
        initComponents();
        mainMenuBtn.setVisible(false);
        signOutBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        savingsBtn = new javax.swing.JButton();
        chequingBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        signOutBtn = new javax.swing.JButton();
        amountComboBox = new javax.swing.JComboBox<>();
        lbl_ckBank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 26, 53));

        savingsBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        savingsBtn.setForeground(new java.awt.Color(0, 26, 53));
        savingsBtn.setText("Withdraw from Savings");
        savingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsBtnActionPerformed(evt);
            }
        });

        chequingBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        chequingBtn.setForeground(new java.awt.Color(0, 26, 53));
        chequingBtn.setText("Withdraw from Chequing");
        chequingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequingBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mainMenuBtn.setForeground(new java.awt.Color(0, 26, 53));
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        signOutBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        signOutBtn.setForeground(new java.awt.Color(0, 26, 53));
        signOutBtn.setText("Sign Out");
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        amountComboBox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        amountComboBox.setForeground(new java.awt.Color(0, 26, 53));
        amountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amount", "20", "50", "100", "500", "1000" }));
        amountComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountComboBoxActionPerformed(evt);
            }
        });

        lbl_ckBank.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lbl_ckBank.setForeground(new java.awt.Color(51, 61, 174));
        lbl_ckBank.setText("Ck BANK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(amountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chequingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savingsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_ckBank)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(signOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(mainMenuBtn)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_ckBank)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(savingsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chequingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(amountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(mainMenuBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signOutBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * This method allows the user to choose their savings account as their source
 * withdrawal. The method checks if the savings account has sufficient funds before
 * it is deducted from its value. 
 * 
 * @param evt 
 */
    private void savingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsBtnActionPerformed
         UIManager.put("OptionPane.messageFont", new FontUIResource(new Font(  
          "Century Gothic", Font.PLAIN, 12))); 
        if((ATM.sufficientFundsChequing(Integer.parseInt((String) amountComboBox.getSelectedItem())))==false)
        {
             JOptionPane.showMessageDialog(this, "Account does not have sufficient funds.");  
              
        }
        else
        ATM.withdrawlSavings(Integer.parseInt((String) amountComboBox.getSelectedItem())); 
        mainMenuBtn.setVisible(true);
        signOutBtn.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_savingsBtnActionPerformed
/**
 * This method allows the user to choose their chequing account as their source
 * withdrawal. The method checks if the chequing account has sufficient funds before
 * it is deducted from its value. 
 * 
 * @param evt 
 */
    private void chequingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequingBtnActionPerformed
        if((ATM.sufficientFundsSavings(Integer.parseInt((String) amountComboBox.getSelectedItem())))==false)
        {
             JOptionPane.showMessageDialog(this, "Account does not have sufficient funds.");  
              
        }
        else
        ATM.withdrawlChequing(Integer.parseInt((String) amountComboBox.getSelectedItem())); 
        mainMenuBtn.setVisible(true);
        signOutBtn.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_chequingBtnActionPerformed
        /** This method allows the user to proceed onto the UserChoices class.
         * 
         * @param evt Holds data of the action performed by the user on the control.           
         */
    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        this.setVisible(false);
        UserChoices userChoices = new UserChoices();
        userChoices.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuBtnActionPerformed
    /** This method allows the user to proceed onto the FrontPage class.
         * 
         * @param evt Holds data of the action performed by the user on the control.           
         */
    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        this.setVisible(false);
        FrontPage frontPage = new FrontPage();
        frontPage.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void amountComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdrawl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> amountComboBox;
    private javax.swing.JButton chequingBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ckBank;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton savingsBtn;
    private javax.swing.JButton signOutBtn;
    // End of variables declaration//GEN-END:variables
}
